### ISSUE TITLE
Fix references to LTLMoP Github organization

### ISSUE THREAD

**Issue by spmaniato** [johnyf/openpromela#4]
@johnyf , whenever you get the chance, I suggest that you fix the [references to LTLMoP](https://github.com/johnyf/openpromela/search?utf8=%E2%9C%93&q=LTLMoP) since the organization has been renamed to https://github.com/VerifiableRobotics

Github will automatically redirect them, so this is not urgent.

**Comment by johnyf** [comment]
Thanks for the update, I relied on the redirects. As of cdb6d03194c1ee41718b05d27a9db9b6152cfb6c, `slugs` is not used.

**Comment by spmaniato** [comment]
Roger. I may give `omega` a try (pure Python :heart: )
